// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace News_Database_First.Models;

[Table("Author")]
public partial class Author
{
    [Key]
    public int Id { get; set; }

    [Required]
    public string Name { get; set; }

    public DateTime JoinDate { get; set; }

    [Required]
    public string Username { get; set; }

    [Required]
    public string Password { get; set; }

    [Required]
    public string Brief { get; set; }

    [InverseProperty("Auth")]
    public virtual ICollection<News> News { get; set; } = new List<News>();
    public  string ToString()
    {
        return $"{Id}-{Name}-{Brief}";
    }
}