// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace News_Database_First.Models;

public  class Cataloge
{
    [Key]
    public int Id { get; set; }

    [Required]
    public string Name { get; set; }

    [Required]
    public string Description { get; set; }

    [InverseProperty("Cat")]
    public virtual ICollection<News> News { get; set; } = new List<News>();
    public   string ToString() => $"{Id}-{Name}-{Description}";
}