// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace News_Database_First.Models;

[Index("AuthId", Name = "IX_News_auth_id")]
[Index("CatId", Name = "IX_News_cat_id")]
public partial class News
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Required]
    [Column("name")]
    public string Name { get; set; }

    [Required]
    [Column("description")]
    public string Description { get; set; }

    [Column("datetime")]
    public DateTime Datetime { get; set; }

    [Column("cat_id")]
    public int CatId { get; set; }

    [Column("auth_id")]
    public int AuthId { get; set; }

    [ForeignKey("AuthId")]
    [InverseProperty("News")]
    public virtual Author Auth { get; set; }

    [ForeignKey("CatId")]
    [InverseProperty("News")]
    public virtual Cataloge Cat { get; set; }

}